development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bodendaten_chem_development
  username: root
  password:
  hostname: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bodendaten_chem_test
  username: root
  password:
  hostname: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bodendaten_chem_development
  username: root
  password:
  hostname: 127.0.0.1
